import { z } from 'zod'

export const ROUTING_REASON_CODES = [
  'CAPABILITIES_SATISFIED',
  'FAST_PATH_PREFERRED',
  'REQUESTED_RUNTIME_PREFERENCE',
  'TENANT_RUNTIME_PREFERENCE',
  'CANDIDATE_UNHEALTHY',
  'CANDIDATE_DEGRADED',
  'CANDIDATE_NOT_CONFIGURED',
  'CANDIDATE_FORBIDDEN_BY_POLICY',
  'RUNTIME_FORBIDDEN_BY_POLICY',
  'RUNTIME_PREFERENCE_REQUIRED',
  'SESSION_DURATION_UNSUPPORTED',
  'CANDIDATE_BLOCKED_BY_SAFETY',
  'REQUIRED_CAPABILITY_UNSUPPORTED',
  'REQUIRES_WEBGL',
  'REQUIRES_VIDEO',
  'REQUIRES_PERSISTENT_AUTH',
  'REQUIRES_REAL_BROWSER_TLS',
  'CAPABILITY_UNKNOWN',
  'CAPABILITY_EXPERIMENTAL_NOT_ALLOWED',
  'PREFERRED_CAPABILITY_MATCH',
  'DOMAIN_COMPATIBILITY_LOW',
  'PROVIDER_RATE_LIMITED',
  'PROVIDER_CAPACITY_EXHAUSTED',
  'SELECTED_HIGHEST_SCORE',
  'LOWER_SCORE',
  'STABLE_TIE_BREAK',
  'NO_COMPATIBLE_RUNTIME',
  'FALLBACK_ELIGIBLE',
  'FALLBACK_NOT_ELIGIBLE',
  'FALLBACK_DISABLED',
  'FALLBACK_CANDIDATE_UNAVAILABLE',
  'FALLBACK_SAME_RUNTIME',
  'FALLBACK_FROM_RUNTIME',
  'FALLBACK_LIMIT_REACHED',
] as const

export const RoutingReasonCodeSchema = z.enum(ROUTING_REASON_CODES)
export type RoutingReasonCode = z.infer<typeof RoutingReasonCodeSchema>

export const ROUTING_REASON_DESCRIPTIONS = {
  CAPABILITIES_SATISFIED: 'The candidate satisfies every required capability.',
  FAST_PATH_PREFERRED: 'The versioned policy prefers this efficient runtime.',
  REQUESTED_RUNTIME_PREFERENCE: 'The candidate matches the caller runtime preference.',
  TENANT_RUNTIME_PREFERENCE: 'The candidate matches the tenant runtime preference.',
  CANDIDATE_UNHEALTHY: 'The candidate provider is unavailable.',
  CANDIDATE_DEGRADED: 'The candidate provider is degraded.',
  CANDIDATE_NOT_CONFIGURED: 'The candidate provider is not configured.',
  CANDIDATE_FORBIDDEN_BY_POLICY: 'Tenant policy forbids the provider.',
  RUNTIME_FORBIDDEN_BY_POLICY: 'Tenant policy forbids the runtime.',
  RUNTIME_PREFERENCE_REQUIRED:
    'Fallback is disabled and the candidate is not the requested runtime.',
  SESSION_DURATION_UNSUPPORTED: 'The candidate cannot satisfy the requested session duration.',
  CANDIDATE_BLOCKED_BY_SAFETY: 'A product safety constraint blocks the candidate.',
  REQUIRED_CAPABILITY_UNSUPPORTED: 'A required capability is unsupported.',
  REQUIRES_WEBGL: 'The workload requires WebGL.',
  REQUIRES_VIDEO: 'The workload requires video.',
  REQUIRES_PERSISTENT_AUTH: 'The workload requires persistent authentication.',
  REQUIRES_REAL_BROWSER_TLS: 'The workload requires real-browser TLS behavior.',
  CAPABILITY_UNKNOWN: 'Support for a required capability is unknown.',
  CAPABILITY_EXPERIMENTAL_NOT_ALLOWED: 'Experimental support was not permitted.',
  PREFERRED_CAPABILITY_MATCH: 'The candidate satisfies a preferred capability.',
  DOMAIN_COMPATIBILITY_LOW: 'The supplied compatibility signal is low.',
  PROVIDER_RATE_LIMITED: 'The provider is rate limited.',
  PROVIDER_CAPACITY_EXHAUSTED: 'The provider has no capacity for a new session.',
  SELECTED_HIGHEST_SCORE: 'The candidate won the deterministic comparison.',
  LOWER_SCORE: 'Another eligible candidate had a higher deterministic score.',
  STABLE_TIE_BREAK: 'The stable tie-break selected another equally scored candidate.',
  NO_COMPATIBLE_RUNTIME: 'No candidate satisfies every hard constraint.',
  FALLBACK_ELIGIBLE: 'The allocation failure is safe for bounded runtime fallback.',
  FALLBACK_NOT_ELIGIBLE: 'The failure must not trigger runtime fallback.',
  FALLBACK_DISABLED: 'The effective policy disables automatic runtime fallback.',
  FALLBACK_CANDIDATE_UNAVAILABLE: 'No distinct fallback candidate was supplied.',
  FALLBACK_SAME_RUNTIME: 'The fallback candidate does not cross to a distinct runtime.',
  FALLBACK_FROM_RUNTIME: 'The state moved from the original runtime to one fallback runtime.',
  FALLBACK_LIMIT_REACHED: 'The maximum cross-runtime fallback count was reached.',
} as const satisfies Readonly<Record<RoutingReasonCode, string>>
